### ISSUE TITLE
Remove unused methods and vars

### ISSUE THREAD

**Issue by augarov** [eltech-anykeyers/gm_attractor#1]
https://github.com/eltech-anykeyers/gm_attractor/blob/69b1b39ff16614c43a9cdc608f5ebd33762aa74a/src/attractorglapp.cpp#L32
https://github.com/eltech-anykeyers/gm_attractor/blob/69b1b39ff16614c43a9cdc608f5ebd33762aa74a/src/attractorglapp.cpp#L206

Unnecessary stuff. We don't use it anymore.

**Comment by andixlm** [comment]
Миленько. Удалю.
